version: '3.7'

services:
  frontend:
    container_name: client
    build:
        context: ./client
        dockerfile: Dockerfile
    image: keithcruz/client
    ports:
        - "3000:3000"
    volumes:
        - ./client:/usr/src/app
  backend:
      container_name: server
      build:
          context: ./server
          dockerfile: Dockerfile
      image: keithcruz/server
      ports:
          - "8080:8080"
      volumes:
          - ./server:/usr/src/app
